### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by ismay** [metalsmith/metalsmith-rss#4]
Hi @MoOx, how would you feel about moving this plugin to the metalsmith org? The metalsmith core devs could help out with maintenance and you could still keep your permissions of course. Let me know what you think!

**Comment by MoOx** [comment]
Yeah sure. Can you give me more detail for the transfer?

**Comment by ismay** [comment]
Sure, what details would you need? Here's the org: https://github.com/metalsmith

**Comment by MoOx** [comment]
> You don’t have the permission to create repositories on metalsmith

I am giving it to you so you can do whatever you want with it. What's your npm username?

**Comment by ismay** [comment]
Thanks. I've moved it to the metalsmith org. I'm not sure which npm user would be the most convenient. @woodyrew what would be most convenient for the org?

**Comment by woodyrew** [comment]
@ismay You and me ( @woodyrew ) seems reasonable to me at this point.

**Comment by MoOx** [comment]
Done.

**Comment by ismay** [comment]
Cool, thanks!
